# Generated by Django 2.1.3 on 2018-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_barang_diskon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='diskon',
            field=models.IntegerField(default=0, verbose_name='Diskon'),
        ),
    ]
