# Generated by Django 2.1.3 on 2018-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_barang_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='diskon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diskon'),
        ),
    ]
